global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:7860']
remote_write:
- url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
  basic_auth:
    username: 1386329 
    password: glc_eyJvIjoiMTAzNTc2NiIsIm4iOiJkZWZhdWx0LXRva2VuLW5hbWUtZGVmYXVsdC10b2tlbi1uYW1lLWhlcmUiLCJrIjoiNlU1YjIwMlZjajIyckcyYVo1OXlzYUhEIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
