# global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   evaluation_interval: 15s
# remote_write:
# - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
#   basic_auth:
#     username: 1386329
#     password: glc_eyJvIjoiMTAzNTc2NiIsIm4iOiJkZWZhdWx0LXRva2VuLW5hbWUtZGVmYXVsdC10b2tlbi1uYW1lLWhlcmUiLCJrIjoiNlU1YjIwMlZjajIyckcyYVo1OXlzYUhEIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
# scrape_configs:
#   - job_name: 'app'
#     honor_timestamps: true
#     scheme: http
#     metrics_path: '/metrics'
#     scrape_interval: 15s
#     scrape_timeout: 10s
#     static_configs:
#       - targets:
#         - localhost:7860

global:
  scrape_interval: 10s
scrape_configs:
  - job_name: node
    static_configs:
      - targets:
        - localhost:9100
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:7860
remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: 1386329
      password: glc_eyJvIjoiMTAzNTc2NiIsIm4iOiJzdGFjay04MzgwMzYtaG0td3JpdGUtdGVzdF90dXRvX2dyYWZhbmFfMiIsImsiOiIxS1E1SndJOThZdDU0dTZDSW9iNWJDOTIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
